---
title: "Single Cell RNA-seq Analysis of GSE279086"
author: "Abdul Kader Ibrahim"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
---
```{r Setting my working directory to WSL}
setwd("//wsl$/Ubuntu/home/abdul/single-cell-portfolio/sc-portfolio")

```

```{r Load the packages}
library(Seurat)
library(dplyr)
library(tidyr)
```

``` {r Prepare the seurat object: List all GSM subdirectories}
data_dir <- "/home/abdul/single-cell-portfolio/sc-portfolio/GSE279086/raw_geo_data"
samples <- list.dirs(data_dir, recursive = FALSE)
samples
```



``` {r Create seurat_list with 40 Individual seurat objects}
library(Seurat)
seurat_list <- lapply(samples, function(sample_path) {
  sample_name <- basename(sample_path)
  message("Processing: ", sample_name)
  
  #Load data - 40 samples (Read10X doesn't work because sample names are different, so using ReadMtx instead)

  counts <- suppressWarnings (Read10X (data.dir = sample_path))
 
  #Create Seurat objects - 40 objects

  seurat_obj <- CreateSeuratObject(counts = counts, project = sample_name, min.cells = 3,min.features = 200, assay = "RNA")
  
  # Add sample name metadata and calculate percent.mt and percent.rb
  
  seurat_obj$sample <- sample_name

  seurat_obj[["percent.mt"]] <- PercentageFeatureSet(seurat_obj, pattern = "^MT-")
  seurat_obj[["percent.rb"]] <- PercentageFeatureSet(seurat_obj, pattern = "^RP[SL]|RPLP")
  
  # Handle missing values in percent.mt and percent.rb
  seurat_obj@meta.data <- seurat_obj@meta.data %>%
    mutate(
      percent.mt = replace_na(percent.mt, 0),
      percent.rb = replace_na(percent.rb, 0)
    )

  message(paste0("NaNs remaining in 'percent.mt': ", sum(is.nan(seurat_obj$percent.mt))))
  message(paste0("NaNs remaining in 'percent.rb': ", sum(is.nan(seurat_obj$percent.rb))))

  return (seurat_obj)
 
})


length(seurat_list) 
names(seurat_list) <- basename(samples)
names(seurat_list)
```
```{r Checking the seurat_list and seurat_object}
length(seurat_list)      # How many samples were loaded (should be 40)
names(seurat_list)       # Names of each Seurat object (sample IDs)

seurat_list[[1]]         # Overview of the first object
dim(seurat_list[[1]])    # Genes × cells
head(seurat_list[[1]]@meta.data)   # Metadata table

head(seurat_list[[1]]$percent.mt)
head(seurat_list[[1]]$percent.rb)


#This gives you a compact overview of how many cells and genes each Seurat object contains.
lapply(seurat_list, function(obj) {
  c(
    sample = unique(obj$sample),
    cells = ncol(obj),
    genes = nrow(obj)
  )
})


```


```{r Save 40 individual samples into separate 40 seurat objects}
output_dir <- file.path("./GSE279086/input")

if (!dir.exists(output_dir)) {
  dir.create(output_dir, recursive = TRUE)
}

# Save each Seurat object
for (i in seq_along(seurat_list)) {
  sample_name <- seurat_list[[i]]@project.name
  save_path <- file.path(output_dir, paste0(sample_name, "_seurat.rds"))
  
  message("Saving: ", sample_name, " -> ", save_path)
  saveRDS(seurat_list[[i]], file = save_path)
}

message("All Seurat objects saved successfully in: ", output_dir)
```

