---
title: "QC and Batch Correction of GSE279086"
author: "Abdul Kader Ibrahim"
date: "2026-02-15"
output: html_document
---

```{r Load the packages}
library(Seurat)
library(SeuratDisk)
library(dplyr)
library(R.utils)  
library(ggplot2)
library(ggExtra)
library(RColorBrewer)
library(openxlsx)
library(dplyr)
library(scales)
library(HGNChelper)
library(dittoSeq)
library(harmony)
library(batchelor)

library(SingleCellExperiment)
```


```{r}

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GEOquery")

library (GEOquery)

BiocManager::install("zellkonverter")
library(zellkonverter)
```


```{r Plotting to check how many cells each sample contributed}
# Count cells per sample
cell_counts <- table(seurat_combined$orig.ident)

# Bar plot
barplot(cell_counts,
        las = 2,                # rotate sample labels
        col = "steelblue",
        main = "Cell counts per sample",
        ylab = "Number of cells")
```


```{r Adding 'Condition' col to the seurat object to do qc plot much better}
seurat_combined <- readRDS(file = paste0(outputDir, "GSE279086_seurat_combined.rds"))

table(seurat_combined$orig.ident)
gsm_ids <- unique(seurat_combined$orig.ident)

gse <- getGEO("GSE279086", GSEMatrix = TRUE)
meta <- pData(gse[[1]])
dim(meta)
colnames(meta)
meta$`disease:ch1`

table(meta$`disease:ch1`) #"Lean Control 12" "Type 1 Diabetes 28"

#Condtion to be analyzed = Lean Control vs T1D

meta$disease_clean <- ifelse(
  meta$`disease:ch1` == "Lean Control",
  "Control",
  "Type 1 Diabetes"
)
table(meta$disease_clean)

condition_map <- meta$disease_clean
names(condition_map) <- meta$geo_accession
View (condition_map)

# Add condition to each cell - cell level condition vector
seurat_combined$Condition <- unname(condition_map[seurat_combined$orig.ident])

#Check for any missing value
table(seurat_combined$Condition)
sum(is.na(seurat_combined$Condition))
```


```{r Explore Genes,mito, RB genes before QC - Summary Stat }
head(rownames(seurat_combined), 20)


colnames(seurat_combined@meta.data)

summary(seurat_combined$percent.mt)
summary(seurat_combined$percent.rb)

```


#.................Perform QC..............#
# These parameters define quality control rules that help distinguish real, healthy single cells from empty droplets, dying cells, or technical artifacts.

```{r Pre-QC violin plot to see distribution of genes, counts,MT and RB genes}
study_id <- "GSE279086"


save_violin_plots_separate <- function(
  seurat_obj,
  plotDir,
  study_id,
  features = c("nCount_RNA", "nFeature_RNA", "percent.mt", "percent.rb")
) {

  if (!dir.exists(plotDir)) {
    dir.create(plotDir, recursive = TRUE)
  }

  meta <- seurat_obj@meta.data
  meta$sample <- as.factor(meta$orig.ident)

  for (feat in features) {

    if (!feat %in% colnames(meta)) {
      warning(paste("Skipping", feat, "- not found in metadata"))
      next
    }

    p <- ggplot(meta, aes(x = sample, y = .data[[feat]])) +
      geom_violin(trim = TRUE, fill = "steelblue", alpha = 0.7) +
      geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.6) +
      labs(
        title = feat,
        x = "Sample",
        y = feat
      ) +
      theme_bw(base_size = 14) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title  = element_text(hjust = 0.5)
      )

    ggsave(
      filename = file.path(
        plotDir,
        paste0(study_id, "_preQC_", feat, "_violin.png")
      ),
      plot  = p,
      width = 16,
      height = 9,
      dpi   = 400,
      bg    = "white"
    )
  }
}

save_violin_plots_separate(seurat_combined, plotDir, study_id)

# Scatter plot of nCount vs nFeature with marginal histograms
density_scatter_plot <- function(seurat_obj, filename){
  df <- data.frame(
    log1p_nCount_RNA = log1p(seurat_obj$nCount_RNA),
    log1p_nFeature_RNA = log1p(seurat_obj$nFeature_RNA),
    Condition = seurat_obj$Condition
  )
  
  p <- ggplot(df, aes(x = log1p_nCount_RNA, y = log1p_nFeature_RNA, colour = Condition)) +
    geom_point(alpha = 0.3, size = 0.5) +
    theme_minimal() +
    theme(legend.position.inside = c(0.05, 0.95), legend.justification = c("left", "top"), legend.key.size = unit(0.5, 'cm')) +
    guides(color = guide_legend(override.aes = list(size = 5))) + # 'size' here controls the symbol size
    labs(x = "log1p(nCount_RNA)", y = "log1p(nFeature_RNA)")
  
  p <- ggMarginal(p, type = "histogram", fill = "skyblue", bins = 40)
  ggsave(
  filename,
  plot = p,
  width = 8,
  height = 10,
  dpi = 400,
  bg = "white"
)

}

density_scatter_plot(seurat_combined, file.path(plotDir, paste0(study_id, "_preQC_density-scatter.png")))
```

```{r Actual QC Steps - Define functions to Remove outlier cells by Mahalanobis,empty cells, doublets, dead cells}
# Remove cells with abnormal total RNA counts; automatically detects outliers
fil_nCounts <- function(seurat_obj, threshold_mahalanobis){
  ncounts_data <- as.data.frame(seurat_obj@meta.data$nCount_RNA)
  colnames(ncounts_data) <- "nCount_RNA"
  
  mahalanobis_dist <- mahalanobis(
    x = ncounts_data,
    center = colMeans(ncounts_data),
    cov = cov(ncounts_data)
  )
  
  seurat_obj$mahal_dist_nCount <- mahalanobis_dist
  mahal.fil <- qchisq(threshold_mahalanobis, df = ncol(ncounts_data))
  message(paste0("Mahalanobis threshold: ", round(mahal.fil, 3)))
  
  cells_to_remove <- rownames(seurat_obj@meta.data)[seurat_obj$mahal_dist_nCount > mahal.fil]
  message(paste0("Removing ", length(cells_to_remove), " cells (outliers by nCount_RNA)"))
  
  return(subset(seurat_obj, cells = setdiff(colnames(seurat_obj), cells_to_remove)))
}

# Filter low (empty droplets or poor capture) & high (likely doublets) gene cells
filter_nFeatures <- function(seurat_obj, min_feat, max_feat, ...) {
  return(subset(seurat_obj, subset = nFeature_RNA > min_feat & nFeature_RNA < max_feat))
}

# Filter high mitochondrial RNA 
filter_mt <- function(seurat_obj, max_mt) {
  return(subset(seurat_obj, subset = percent.mt < max_mt))
}

# Filter high ribosomal RNA 
filter_rb <- function(seurat_obj, max_rb) {
  return(subset(seurat_obj, subset = percent.rb < max_rb))
}

```


```{r QC thresholds and QC filtered seurat}
study_id <- "GSE279086"
min_features    <- 200  # A cell must express at least 200 genes to be considered real. <200 --> empty droplets/cause most noise
max_features    <- 7000 # Cells with more than 7000 genes are removed. Extremely high gene counts often indicate doublets
max_percent_mt  <- 15 # Remove cells where >20% of RNA comes from mitochondria
max_percent_rb  <- 10 # Remove cells dominated by ribosomal expression. High rRNA --> low info content/technical bias
threshold_mahalanobis <- 0.95  # Remove the worst 5% of cells that look abnormal overall (catches subtle outliers)

seurat_filtered <- filter_nFeatures(seurat_combined, min_features, max_features)

seurat_filtered <- filter_mt(seurat_filtered, max_percent_mt)

seurat_filtered <- fil_nCounts(seurat_filtered, threshold_mahalanobis)

seurat_filtered <- filter_rb(seurat_filtered,max_percent_rb)

# Cell counts before QC
df_pre_qc <- as.data.frame(table(seurat_combined$Sample))
colnames(df_pre_qc) <- c("Sample_ID", "Cells_Before_QC")

# Cell counts after QC
df_post_qc <- as.data.frame(table(seurat_filtered$Sample))
colnames(df_post_qc) <- c("Sample_ID", "Cells_After_QC")

# Merge into final QC table (left join behavior)
final_qc_table <- merge(
  df_pre_qc,
  df_post_qc,
  by = "Sample_ID",
  all.x = TRUE
)

final_qc_table
total_cells_before_qc <- sum(final_qc_table$Cells_Before_QC, na.rm = TRUE)
total_cells_after_qc  <- sum(final_qc_table$Cells_After_QC, na.rm = TRUE)

total_cells_before_qc
total_cells_after_qc

dim (seurat_combined)
dim (seurat_filtered)
```

```{r Save Summary Table (Cells pre vs post QC) as CSV to output folder}
qc_metrics_file <- file.path(outputDir, paste0(study_id, "_QC_metrics.csv"))
write.csv(final_qc_table, qc_metrics_file, row.names = FALSE)
cat("Saved QC summary table to:", qc_metrics_file, "\n")
```


```{r Visualize and plot post QC data}
study_id <- "GSE279086"

save_violin_plots_separate <- function(
  seurat_obj,
  plotDir,
  study_id,
  features = c("nCount_RNA", "nFeature_RNA", "percent.mt", "percent.rb")
) {

  # Ensure output directory exists
  if (!dir.exists(plotDir)) {
    dir.create(plotDir, recursive = TRUE)
  }

  meta <- seurat_obj@meta.data
  meta$sample <- as.factor(meta$orig.ident)

  for (feat in features) {

    if (!feat %in% colnames(meta)) {
      warning(paste("Skipping", feat, "- not found in metadata"))
      next
    }

    p <- ggplot(meta, aes(x = sample, y = .data[[feat]])) +
      geom_violin(trim = TRUE, fill = "steelblue", alpha = 0.7) +
      geom_boxplot(width = 0.1, outlier.shape = NA, alpha = 0.6) +
      labs(
        title = feat,
        x = "Sample",
        y = feat
      ) +
      theme_bw(base_size = 14) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1),
        plot.title  = element_text(hjust = 0.5)
      )

    ggsave(
      filename = file.path(
        plotDir,
        paste0(study_id, "_postQC_", feat, "_violin.png")
      ),
      plot  = p,
      width = 16,
      height = 9,
      dpi   = 400,
      bg    = "white"
    )
  }
}

save_violin_plots_separate(seurat_filtered, plotDir, study_id)

# Scatter plot of nCount vs nFeature with marginal histograms
density_scatter_plot <- function(seurat_obj, filename){
  df <- data.frame(
    log1p_nCount_RNA = log1p(seurat_obj$nCount_RNA),
    log1p_nFeature_RNA = log1p(seurat_obj$nFeature_RNA),
    Condition = seurat_obj$Condition
  )
  
  p <- ggplot(df, aes(x = log1p_nCount_RNA, y = log1p_nFeature_RNA, colour = Condition)) +
    geom_point(alpha = 0.3, size = 0.5) +
    theme_minimal() +
    theme(legend.position.inside = c(0.05, 0.95), legend.justification = c("left", "top"), legend.key.size = unit(0.5, 'cm')) +
    guides(color = guide_legend(override.aes = list(size = 5))) + # 'size' here controls the symbol size
    labs(x = "log1p(nCount_RNA)", y = "log1p(nFeature_RNA)")
  
  p <- ggMarginal(p, type = "histogram", fill = "skyblue", bins = 40)
  ggsave(
  filename,
  plot = p,
  width = 8,
  height = 10,
  dpi = 400,
  bg = "white"
)

}

density_scatter_plot(seurat_filtered, file.path(plotDir, paste0(study_id, "_postQC_density-scatter.png")))
```



#BATCH CORRECTION STEPS

```{r Keep only protein coding genes}
protein_coding_genes <- readLines("./Protein_coding_genes.txt")

# Subset BEFORE normalization
seurat_filtered <- subset(seurat_filtered, features = protein_coding_genes)

####  Explore Filtered Seurat Object after QC Filter  ####
class(seurat_filtered)            # Seurat class
Assays(seurat_filtered)           # assays available in the rds
DefaultAssay(seurat_filtered)     # default/active assay in the rds
dim(seurat_filtered)              # 16832 genes/features x 6327 cells
```

```{r Save Filtered Seurat Object}
saveRDS(seurat_filtered, file = paste0(outputDir,"GSE279086_seurat_qc_filtered.rds"))
seurat_filtered <- readRDS(file = paste0(outputDir, "GSE279086_seurat_qc_filtered.rds"))
```

```{r Standard workflow for normalization and scaling}
cat("Normalizing data using LogNormalize method (scale factor = 10,000)...\n")
seurat_processed <- NormalizeData(seurat_filtered,
                                 normalization.method = "LogNormalize")  # What percentage of total RNA does each gene contribute in this cell?

seurat_processed <- FindVariableFeatures(seurat_processed, selection.method = "vst", nfeatures = 2500)
seurat_processed <- ScaleData(seurat_processed) 
seurat_processed <- RunPCA(seurat_processed, dims=1:100, npcs = 100)
```

```{r Custom colors for Condition in metadata}
custom_colors <- c("CONTROL"="blue", "T1D"="darkorange3")
```

```{r Elbow Plot}
# Get the standard deviation for each PC then get the variance explained by each PC, then calculate the cumulative variance
stdev <- seurat_processed[["pca"]]@stdev
var_explained <- stdev^2 / sum(stdev^2)
cum_var <- cumsum(var_explained)
pca_var_df <- data.frame(
  PC = 1:length(stdev),
  Variance = var_explained,
  CumulativeVariance = cum_var
)
pca_var_df
num_PCs <- min(which(cum_var >= 0.95))  # first PC where cumulative variance >= 85%
num_PCs

elbow_plot <- ElbowPlot(seurat_processed, ndims = 100, reduction = 'pca')+
  labs(title = "PCA Elbow Plot for Dimensionality Selection")

ggsave(file.path(plotDir, paste0(study_id, "_ElbowPlot.png")),
       elbow_plot, width = 8, height = 6, bg = 'white')
```

```{r Total variance explained across the top 35 PCs (based on elbow plot)}
pca_stdev <- seurat_processed[["pca"]]@stdev
pca_var_explained <- (pca_stdev^2) / sum(pca_stdev^2) * 100
total_var<- sum(pca_var_explained[1:35])
cat("Total variance explained by top PCs:", round(total_var, 2), "%\n")
```

```{r Perform UMAP & Clustering on unintegrated data}
library(glue)
seurat_processed <- RunUMAP(seurat_processed, dims = 1:35)
seurat_processed <- FindNeighbors(seurat_processed, dims = 1:35, reduction = "pca", graph.name = "pca_nn")

seurat_processed <- FindClusters(seurat_processed, resolution = 0.8,graph.name = "pca_nn", cluster.name = "pca_clusters") 
n_clusters <- length(unique(seurat_processed$pca_clusters))
cat(glue("Clustering complete. Number of clusters: {n_clusters}\n"))  # 25 clusters found

head(seurat_processed@meta.data, 3)
```

```{r Save Unintegrated Seurat Object}
saveRDS(seurat_processed, file = paste0(outputDir,"GSE279086_seurat_pca_umap.rds"))
seurat_processed <- readRDS(file = paste0(outputDir, "GSE279086_seurat_pca_umap.rds"))

merged = JoinLayers(seurat_processed) 
sce <- as.SingleCellExperiment(merged, assay = "RNA")

dim(sce)
assayNames(sce)
reducedDimNames(sce)
head(colData(sce),2)



outputDir <- "./GSE279086/output"
h5seurat_name <- "GSE279086_seurat_pca_umap.h5seurat"
h5ad_name <- "GSE279086_seurat_pca_umap.h5ad"
SaveH5Seurat(
  object = seurat_processed,
  filename = file.path(outputDir, h5seurat_name),
  overwrite = TRUE,
  version = "3"
)

writeH5AD(sce, file = paste0(outputDir, "GSE279086_seurat_pca_umap(1).h5ad"))
```


```{r Run Harmony & Perform Clustering on Harmony integrated data}
harmony_processed <- RunHarmony(seurat_processed, c("Sample"), plot_convergence = TRUE)

harmony_processed <- RunUMAP(harmony_processed, reduction = "harmony", dims = 1:50)

harmony_processed <- FindNeighbors(harmony_processed, reduction = "harmony", dims = 1:50, graph.name = "harmony_nn")

harmony_processed <- FindClusters(harmony_processed, graph.name = "harmony_nn", resolution = 0.8, group.name = "Harmony_clusters")
#found 20 clusters

saveRDS(harmony_processed, file = paste0(outputDir,"GSE279086_harmony_corrected.rds"))
#harmony_processed <- readRDS(file = paste0(outputDir, "GSE279086_harmony_corrected.rds"))

merged1 = JoinLayers(harmony_processed) 
sce_harmony <- as.SingleCellExperiment(merged1, assay = "RNA")

dim(sce_harmony)
assayNames(sce_harmony)
reducedDimNames(sce_harmony)
head(colData(sce_harmony),2)

outputDir <- "./GSE279086/output/"
h5seurat_name1 <- "GSE279086_harmony_corrected.h5seurat"
h5ad_name1 <- "GSE279086_harmony_corrected.h5ad"

SaveH5Seurat(
  object = harmony_processed,
  filename = file.path(outputDir, h5seurat_name1),
  overwrite = TRUE,
  version = "3"
)

writeH5AD(sce_harmony, file = paste0(outputDir,  "GSE279086_harmony_corrected.h5ad"))
```

```{r Dimention reduction plot on PCA}
p <- DimPlot(seurat_processed, reduction = "umap", group.by = "Sample") + ggtitle("Uncorrected") +  NoLegend()
  ggtitle("Uncorrected")
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE279086_RawPCA_sample.png"), width = 7, height = 6, dpi = 600)
p

p <-DimPlot(seurat_processed, reduction = "umap", group.by = "Condition") +
  ggtitle("Uncorrected")
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE279086_RawPCA_condition.png"), width = 8, height = 6, dpi = 600)
p
```

```{r Now plot for harmony processed data}
#harmony_processed <- RunUMAP(harmony_processed, reduction = "harmony", dims = 1:30)
p2 <-DimPlot(harmony_processed, reduction = "umap", group.by = "Condition") + ggtitle("Harmony") 
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE279086_Harmony_condition.png"), width = 8, height = 6, dpi = 600)
p2

p <- DimPlot(harmony_processed, reduction = "umap", group.by = "Sample") + ggtitle("Harmony") +  NoLegend()
ggsave(filename = file.path(plotDir, "BENCHMARKING_GSE279086_Harmony_sample.png"), width = 7, height = 6, dpi = 600)
p

umap_hcoords <- Embeddings(harmony_processed, "umap")
write.csv(umap_hcoords, file= paste0 (outputDir, "GSE279086_umap_coordinates.csv"))
```


``` {r Combine Bar Plot}
library(ggplot2)

compute_knn_batch_mixing <- function(
    seu,
    batch_var,
    reduction = "pca",
    dims = 1:50,
    k = 20
){
  
  
  if (!batch_var %in% colnames(seu@meta.data)) {
    stop(paste0("Metadata column '", batch_var, "' not found in seu@meta.data"))
  }
  
  if (!reduction %in% Reductions(seu)) {
    message("[INFO] PCA not found. Running Normalize → HVG → Scale → PCA")
    seu <- NormalizeData(seu, verbose = FALSE)
    seu <- FindVariableFeatures(seu, selection.method = "vst", nfeatures = 3000)
    seu <- ScaleData(seu, verbose = FALSE)
    seu <- RunPCA(seu, npcs = max(dims), verbose = FALSE)
  }
  
  emb <- Embeddings(seu, reduction = reduction)[, dims, drop = FALSE]
  nn  <- FNN::get.knn(emb, k = k)$nn.index
  labs <- seu@meta.data[[batch_var]]
  
  same <- sapply(seq_len(nrow(nn)), function(i){
    mean(labs[nn[i,]] == labs[i], na.rm = TRUE)
  })
  
  df <- data.frame(batch = labs, frac_same_batch = same)
  aggregate(frac_same_batch ~ batch, df, mean)
}

plot_knn_batch_mixing <- function(mix_df){
  ggplot(mix_df, aes(x = batch, y = frac_same_batch)) +
    geom_col(fill = "steelblue") +
    labs(
      title = "Batch Mixing",
      x = "Batch",
      y = "Mean same-batch fraction (higher = stronger batch effect)"
    ) +
    theme_minimal(base_size = 12)
}


batch_column <- "Sample"

mix_df <- compute_knn_batch_mixing(
  seu       = seurat_processed,             
  batch_var = batch_column,
  reduction = "pca",
  dims      = 1:50,
  k         = 20
)

mix_df_harmony <- compute_knn_batch_mixing(
  seu       = harmony_processed,
  batch_var = batch_column,
  reduction = "harmony",
  dims      = 1:50,
  k         = 20
)


mix_df_combined <- rbind(mix_df, mix_df_harmony)


mix_df_combined1 <- rbind(
  transform(mix_df, Status = "Before"),
  transform(mix_df_harmony, Status = "Harmony")
)

```

```{r Final Plot}
batch_cor_plot <- ggplot(mix_df_combined1, aes(x = batch, y = frac_same_batch, fill = Status)) +
  geom_col(position = position_dodge(width = 0.8), width = 0.7) +
  labs(
    title = "Batch Mixing",
    x = "Samples",
    y = "Mean same-batch fraction (higher = stronger batch effect)"
  ) +
  scale_fill_manual(
    values = c(
      "Before" = "#00CED1",     # turquoise
      "Harmony" = "#9370DB"     # new purple shade (example 3rd color)
    )
  ) +
  theme_minimal(base_size = 15) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.title = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5)
  )

batch_cor_plot

ggsave(filename = paste0(plotDir,"batch_correction_barplot_combined.png"), plot = batch_cor_plot, width = 23, height = 8, dpi = 300)
```