name: single-cell
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - r-base=4.3
  - r-essentials
  - r-seurat
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-matrix
  - r-patchwork
  - jupyterlab
  - matplotlib
  - seaborn
